set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR $ENV{CARCH})

# specify the cross compiler
set(CMAKE_C_COMPILER "$ENV{CHOST}-gcc")
set(CMAKE_CXX_COMPILER "$ENV{CHOST}-g++")
set(CMAKE_SYSROOT "$ENV{BUILD_ROOT}/system")

# pkg-config search path
set(ENV{PKG_CONFIG_LIBDIR} "$ENV{BUILD_ROOT}/system/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "$ENV{BUILD_ROOT}")

# extra flags
set(CMAKE_C_FLAGS "-D_QNX_SOURCE ${CMAKE_C_FLAGS} ${EXTRA_CMAKE_C_FLAGS}" )
set(CMAKE_CXX_FLAGS "-D_QNX_SOURCE ${CMAKE_CXX_FLAGS} ${EXTRA_CMAKE_CXX_FLAGS}")
set(CMAKE_ASM_FLAGS "-D_QNX_SOURCE ${CMAKE_ASM_FLAGS} ${EXTRA_CMAKE_ASM_FLAGS}")

set(QNX_LINKER_FLAGS "-lm -lsocket -lgcc_s -lregex")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${QNX_LINKER_FLAGS} ${EXTRA_CMAKE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${QNX_LINKER_FLAGS} ${EXTRA_CMAKE_LINKER_FLAGS}")
